#define ADJ_HIDE_FROM_USER
#include "adj_constants.h"
#include "adj_error_handling.h"
#include "adj_dictionary.h"
#include "adj_adjointer_routines.h"
#include "adj_data_structures.h"
#include "adj_core.h"
#include "adj_debug.h"
#include "adj_adjointer_visualisation.h"
